### ISSUE TITLE
Swift 3 Compatibility

### ISSUE THREAD

**Issue by Maximelc** [luiswdy/SGauge#1]
Hi,

i have updated SGauge for Swift 3 compatibility.
I also added two methods for custom start and end angle.

Can i commit my changes ? 
[SGauge-swift3.zip](https://github.com/luiswdy/SGauge/files/679725/SGauge-swift3.zip)

Thanks :)

**Comment by luiswdy** [comment]
Hi! @Maximelc ,

Sorry that I haven't noticed that you opened the issue. I just saw this recently.

Thank you for migrating SGauge to Swift 3.0 syntax and making a change so that users can customize start and end angles. I merged your change and updated SGauge to the latest Swift 3.0 syntax. Meanwhile, I added your contribution to a new section "Thanks to" in README.md.

Thanks for your contribution! 👍

**Comment by luiswdy** [comment]
Migrated to swift 3.0 syntax.
